DEST?=./dist
default: build.xml build.os.xml build.con.xml build.gui.xml build.jstools.xml
	ant.bat -f build.xml -Ddest=$(DEST)
cleandist:
	ant.bat -f build.xml cleandist
clean:
	ant.bat -f build.xml clean
erase: clean cleandist

